# Generated by Django 5.1.3 on 2024-12-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='ing_list',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.ingredient'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe_list',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.recipe'),
        ),
    ]
