# Generated by Django 5.1.4 on 2024-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='trydef', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
