# Generated by Django 5.1.4 on 2024-12-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_shoppinglist_name_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.shoppinglist'),
        ),
    ]
